"""
Spawn an offspring agent: take a Mating Manifest (synthesis output) plus the
shared agent-template scaffolding, produce a deployable Modal app directory.

After this script runs successfully, `modal deploy <output>/modal_deploy.py`
starts the offspring as a 24/7 Hermes Agent daemon with all its crons,
skills, MCPs, and identity files in place.

Usage:
    python spawn_offspring.py <synthesis_output_dir> <deploy_output_dir>

Example:
    python spawn_offspring.py offspring/run_001 offspring/run_001/deploy

The synthesis dir must contain (created by synthesize_offspring.py):
    SOUL.md
    MEMORY.md
    USER.md
    cron_jobs.json
    MATING_MANIFEST.md (optional)
    raw_manifest.json (optional)

The deploy dir will be created and populated with:
    SOUL.md, MEMORY.md, USER.md, cron_jobs.json   (offspring's identity, copied)
    modal_deploy.py                               (with APP_NAME and VOLUME_NAME set to this offspring)
    bootstrap_crons.py                            (copied from agent-template)
    config.yaml                                   (copied from agent-template)
    requirements.txt                              (copied)
    .env.example                                  (copied)
    mcp/                                          (registry_mcp.py, moltbook_mcp.py, README, etc.)
    skills/                                       (publish_profile.md, protocol_sync.md)
    templates/                                    (agent-profile.html)
    README.md                                     (this offspring's deploy instructions)

Stdlib only. Python 3.10+.
"""
import argparse
import json
import re
import shutil
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent.parent  # .../Blender/
AGENT_TEMPLATE = REPO_ROOT / "agent-template"

REQUIRED_SYNTHESIS_FILES = ["SOUL.md", "MEMORY.md", "USER.md", "cron_jobs.json"]

COPY_FROM_TEMPLATE = [
    "bootstrap_crons.py",
    "config.yaml",
    "requirements.txt",
    ".env.example",
]
COPY_DIRS_FROM_TEMPLATE = ["mcp", "skills", "templates"]


def read_offspring_identity(synth_dir: Path) -> dict:
    """Read the offspring's name and ticker from USER.md."""
    user_md = (synth_dir / "USER.md").read_text(encoding="utf-8")
    name_match = re.search(r"\*\*Name\*\*\s*:\s*([^\n]+)", user_md)
    ticker_match = re.search(r"\*\*Ticker\*\*\s*:\s*\$?([A-Z0-9]+)", user_md)
    niche_match = re.search(r"\*\*Niche\*\*\s*:\s*([^\n]+)", user_md)
    if not name_match:
        raise ValueError(
            "Could not find '**Name**:' in USER.md. "
            "Synthesis output may be malformed."
        )
    return {
        "name": name_match.group(1).strip(),
        "ticker": ticker_match.group(1).strip() if ticker_match else "UNKNOWN",
        "niche": niche_match.group(1).strip() if niche_match else "unknown",
    }


def render_modal_deploy(template_text: str, offspring: dict) -> str:
    """Customize agent-template/modal_deploy.py for this specific offspring."""
    name = offspring["name"]
    app_name = f"blender-{name}"
    volume_name = f"hermes-data-{name}"

    out = template_text
    out = re.sub(
        r'APP_NAME\s*=\s*"[^"]+"',
        f'APP_NAME = "{app_name}"',
        out,
        count=1,
    )
    out = re.sub(
        r'VOLUME_NAME\s*=\s*"[^"]+"',
        f'VOLUME_NAME = "{volume_name}"',
        out,
        count=1,
    )
    # Update the docstring deploy command to reference the new app name
    out = out.replace(
        "modal app stop blender-agent",
        f"modal app stop {app_name}",
    )
    out = out.replace(
        "modal volume rm hermes-data",
        f"modal volume rm {volume_name}",
    )
    return out


def render_deploy_readme(offspring: dict) -> str:
    name = offspring["name"]
    ticker = offspring["ticker"]
    niche = offspring["niche"]
    app_name = f"blender-{name}"
    return f"""# Deploy: {name} ({"$" + ticker})

This directory is a self-contained Modal deployment for the Blender offspring `{name}`. Generated by `spawn_offspring.py` from a Mating Manifest. Locked niche: `{niche}`.

## One-time setup

```
pip install modal
modal token set --token-id <id> --token-secret <secret>
```

## Create the Modal Secret with required credentials

```
modal secret create hermes-secrets \\
    OPENROUTER_API_KEY=<your_openrouter_key> \\
    NEYNAR_API_KEY=<your_neynar_key_if_using_farcaster> \\
    NEYNAR_SIGNER_UUID=<your_signer_uuid_if_posting> \\
    GITHUB_TOKEN=<your_github_pat_scoped_to_blender-agents>
```

Only `OPENROUTER_API_KEY` is strictly required for the daemon to boot. The others enable specific capabilities (Farcaster posting, GitHub self-publish). The agent will run with only OpenRouter and gracefully skip the optional pieces.

## Deploy

```
cd "$(dirname "$0")"
modal deploy modal_deploy.py
```

This starts the agent as a 24/7 daemon. The first 30 seconds:
1. Container builds (image pip-installs hermes-agent)
2. Persistent Modal Volume mounts at /root/.hermes
3. First-boot setup copies this directory's SOUL.md, MEMORY.md, USER.md, cron_jobs.json into the Volume
4. bootstrap_crons.py registers all 9 crons with Hermes Agent
5. hermes gateway start begins; first crons fire on their scheduled times

## Watch it run

```
modal app logs {app_name}
```

You should see (within the first hour):
- `[bootstrap] registered cron: monitoring_scan` etc. for all 9 crons
- `protocol_sync` firing on the hour and reporting "channel-launch bulletin processed"
- `monitoring_scan` firing every 15 min with state checks
- `morning_briefing` firing at the configured time (default 8am UTC) writing a briefing file
- `hourly_action` firing 30 min past each hour with a logged action

## Trigger a cron manually (debugging)

```
modal run {app_name}::manual_cron_trigger --name <cron_name>
```

(Requires adding a `manual_cron_trigger` Modal function to modal_deploy.py; not included by default.)

Or attach to the running container:

```
modal shell {app_name}
# inside the container:
hermes cron run <cron_name>
```

## Tear down

```
modal app stop {app_name}
modal volume rm hermes-data-{name}    # WARNING: destroys persistent state
```

## What's in this directory

- `SOUL.md` - the offspring's persona, terminal goal (LAYER 0 immutable), and identity
- `MEMORY.md` - voice rubric, brand vocab, patterns_that_work, lessons
- `USER.md` - self-model, current operational state, standing posture
- `cron_jobs.json` - 9 cron definitions (5 Tier-1 hygiene immutable + 3 Tier-2 tunable + 1 Tier-3 custom). Read by bootstrap_crons.py at first boot.
- `modal_deploy.py` - Modal app: long-running daemon function + hourly liveness ping. APP_NAME set to `{app_name}`.
- `bootstrap_crons.py` - idempotent cron registrar; runs once at first container boot.
- `config.yaml` - Hermes Agent config: model provider (OpenRouter free Hermes 3 405B), MCP servers wired, terminal backend.
- `mcp/` - local MCP servers (registry, moltbook) + crypto-specific MCPs as added
- `skills/` - publish_profile, protocol_sync, plus any auto-written by Hermes Curator
- `templates/` - agent-profile.html for self-publishing
- `.env.example` - reference for required env vars

## Cost estimate

- Modal compute: ~$2-5/month (0.25 CPU / 512 MB container, 24/7)
- OpenRouter inference: $0 on free Hermes 3 405B tier (rate-limited), or ~$0.20-0.50/day on Hermes 4 70B
- Total: well under the Modal free $30/month credit + OpenRouter free tier

## Where this offspring's revenue ends up

Currently nowhere. Until a real x402 endpoint is deployed via Bankr and a real Clawnch token is launched, the agent operates in simulation: crons fire, posts get written to local Molt Book files, but no USDC moves and no token exists. Adding real revenue plumbing is downstream of this proof-of-life deploy.
"""


def spawn(synth_dir: Path, deploy_dir: Path) -> int:
    if not synth_dir.is_dir():
        print(f"ERROR: synthesis dir not found: {synth_dir}", file=sys.stderr)
        return 1

    missing = [f for f in REQUIRED_SYNTHESIS_FILES if not (synth_dir / f).exists()]
    if missing:
        print(
            f"ERROR: synthesis dir {synth_dir} missing required files: {missing}",
            file=sys.stderr,
        )
        return 1

    if not AGENT_TEMPLATE.is_dir():
        print(
            f"ERROR: agent-template dir not found at {AGENT_TEMPLATE}. "
            "Run spawn_offspring.py from within the Blender repo.",
            file=sys.stderr,
        )
        return 1

    offspring = read_offspring_identity(synth_dir)
    print(
        f"[spawn] offspring name={offspring['name']} "
        f"ticker=${offspring['ticker']} niche={offspring['niche']}"
    )

    deploy_dir.mkdir(parents=True, exist_ok=True)

    # 1. Copy offspring identity files from synthesis output.
    for f in REQUIRED_SYNTHESIS_FILES:
        src = synth_dir / f
        dst = deploy_dir / f
        shutil.copy2(src, dst)
        print(f"[spawn] copied {f} ({src.stat().st_size} bytes)")

    # 2. Copy unchanged scaffolding files from agent-template.
    for f in COPY_FROM_TEMPLATE:
        src = AGENT_TEMPLATE / f
        dst = deploy_dir / f
        if not src.exists():
            print(f"[spawn] WARNING: agent-template/{f} missing, skipping")
            continue
        shutil.copy2(src, dst)
        print(f"[spawn] copied agent-template/{f}")

    # 3. Copy directories from agent-template.
    for d in COPY_DIRS_FROM_TEMPLATE:
        src = AGENT_TEMPLATE / d
        dst = deploy_dir / d
        if not src.is_dir():
            print(f"[spawn] WARNING: agent-template/{d}/ missing, skipping")
            continue
        if dst.exists():
            shutil.rmtree(dst)
        shutil.copytree(src, dst, ignore=shutil.ignore_patterns("__pycache__", "*.pyc"))
        print(f"[spawn] copied agent-template/{d}/")

    # 4. Render modal_deploy.py with this offspring's name baked in.
    src_modal = AGENT_TEMPLATE / "modal_deploy.py"
    if not src_modal.exists():
        print(f"[spawn] ERROR: agent-template/modal_deploy.py missing", file=sys.stderr)
        return 2
    rendered = render_modal_deploy(src_modal.read_text(encoding="utf-8"), offspring)
    (deploy_dir / "modal_deploy.py").write_text(rendered, encoding="utf-8")
    print(
        f"[spawn] rendered modal_deploy.py (APP_NAME=blender-{offspring['name']}, "
        f"VOLUME_NAME=hermes-data-{offspring['name']})"
    )

    # 5. Write the deploy README.
    (deploy_dir / "README.md").write_text(render_deploy_readme(offspring), encoding="utf-8")
    print(f"[spawn] wrote README.md")

    print(f"\n[spawn] done. Deploy with:")
    print(f"    cd {deploy_dir}")
    print(f"    modal deploy modal_deploy.py")
    return 0


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    p.add_argument("synth_dir", type=Path, help="synthesis output dir")
    p.add_argument("deploy_dir", type=Path, help="where to write the deployable dir")
    args = p.parse_args()
    return spawn(args.synth_dir, args.deploy_dir)


if __name__ == "__main__":
    sys.exit(main())
